name: ecgtools-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - codecov
  - dask
  - intake-esm
  - nbsphinx
  - ncar-jobqueue
  - netcdf4
  - numpydoc
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pyyaml
  - rich
  - typer
  - xarray
  - yamale
