name: ecgtools-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - furo
  - joblib
  - jupyterlab
  - myst-nb
  - netcdf4
  - pip
  - pydantic
  - sphinx-copybutton
  - sphinx-inline-tabs
  - xarray
  - pip:
      - sphinxext-opengraph
      - autodoc_pydantic
      - -r ../requirements.txt
      - -e ..
