name: ecgtools-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - fsspec
  - gcsfs
  - intake-esm
  - intake-esm>=2022.09
  - joblib
  - netcdf4
  - pip
  - pre-commit
  - pydantic
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - pyyaml
  - s3fs
  - xarray
