name: ecgtools-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - codecov
  - intake-esm
  - joblib
  - nbsphinx
  - netcdf4
  - numpydoc
  - pip
  - pre-commit
  - pydantic
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - pyyaml
  - rich
  - typer
  - xarray
