name: ecgtools-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - codecov
  - fsspec
  - gcsfs
  - intake-esm >=2022.09
  - joblib
  - nbsphinx
  - netcdf4
  - numpydoc
  - pip
  - pre-commit
  - pydantic
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - pyyaml
  - s3fs
  - typer
  - xarray
  - pip:
      - git+https://github.com/xarray-contrib/cf-xarray
      - git+https://github.com/intake/intake-esm
