name: ecgtools-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - fsspec
  - gcsfs
  - intake-esm
  - joblib
  - netcdf4
  - pip
  - pre-commit
  - pydantic<2.0 # Will remove in upcoming PR
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - pyyaml
  - s3fs
  - xarray
  - pip:
      - git+https://github.com/intake/intake-esm
