name: Upstream CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00” UTC
  workflow_dispatch: # allows you to trigger the workflow run manually

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upstream-dev:
    name: upstream-dev
    runs-on: ubuntu-latest
    if: github.repository == 'ncar-xdev/ecgtools'
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Create conda environment
        id: conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          channel-priority: strict
          cache-env: true
          cache-downloads: true
          micromamba-version: 'latest'
          environment-file: ci/environment-upstream-dev.yml
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install ecgtools
        id: install
        run: |
          python -m pip install -e . --no-deps --force-reinstall
          conda list

      - name: Run Tests
        if: success()
        id: status
        run: |
          python -m pytest -rf --report-log output-log.jsonl
      - name: Generate and publish the report
        if: |
          failure()
          && steps.status.outcome == 'failure'
          && github.event_name == 'schedule'
          && github.repository_owner == 'ncar-xdev'
        uses: xarray-contrib/issue-from-pytest-log@v1
        with:
          log-path: output-log.jsonl
